version: '2.4'

services:
  app:
    image: parser-dev:1.0
    build:
      context: ../
      dockerfile: .dockerdev/Dockerfile
      args:
        RUBY_VERSION: '3.1'
    environment:
      - HISTFILE=/bundle/.bash_history
      - bundler_data:/bundle
    volumes:
      - ..:/app:cached
      - bundler_data:/bundle
    command: bash
    working_dir: /app
    tmpfs:
      - /tmp

volumes:
  bundler_data:
