name: Edge Parser Test

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
    - cron: "10 4 * * */2"
  workflow_dispatch:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_GEMFILE: Gemfile.edge
      EDGE: true
      CI: true
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.4.10", "2.7.1"]
        experimental: [false]
        include:
          - ruby: "head"
            experimental: true
    steps:
    - uses: actions/checkout@v3
    - name: Install Ragel
      run: |
        sudo apt-get update
        sudo apt-get install ragel
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Prepare Parser
      run: |
        bundle exec rake generate
        cp ./lib/parser/rubynext.rb $(bundle show parser)/lib/parser/
        cp -r ./lib/parser/ruby-next $(bundle show parser)/lib/parser/
        (cd $(bundle show parser) && BUNDLE_GEMFILE=Gemfile BUNDLE_PATH=$GITHUB_WORKSPACE/vendor/bundle bundle exec rake generate --trace)
    - name: Run tests
      run: |
        bundle exec rake test
