name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.4.10", "2.5.8", "2.6.6", "2.7.1", "jruby-9.1.17", "jruby-9.2"]
        experimental: [false]
        include:
          - ruby: "head"
            experimental: true

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /home/runner/bundle
        key: bundle-${{ matrix.ruby }}-${{ hashFiles('../Gemfile') }}-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          bundle-${{ matrix.ruby }}-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install Ragel
      run: |
        sudo apt-get update
        sudo apt-get install ragel
    - name: Bundle install
      run: |
        bundle config path /home/runner/bundle
        bundle install
        bundle update
    - name: Run tests
      run: |
        bundle exec rake test
